# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pnpm-version: [7]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Use PNPM ${{ matrix.pnpm-version }}
      uses: pnpm/action-setup@v2.0.1
      with:
        version: ${{ matrix.pnpm-version }}
        run_install: true
    - run: pnpm run --if-present lint 
    - run: pnpm run --if-present build 
